spring:
  application:
    name: "payment"
  config:
    import: "configserver:http://localhost:18071/"

  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

  cloud:
    stream:

      bindings:
        paymentSuccess-out-0:
          destination: payment-success

        paymentFailed-out-0:
          destination: payment-failed

        paymentAuthorized-out-0:
          destination: payment-authorized

      kafka:
        binder:
          brokers:
          - localhost:9092


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "payment"
    description: "Mazadak Payment Service"
    version: "1.0.0"

encrypt:
  key: "44F964E2BEA145629BF5C35EFEE4F"
