spring:
  application:
    name: "payment"

  profiles:
    active: "default"

  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: "/h2-console"


management:
  endpoints:
    web:
      exposure:
        include: "*"

stripe:
  api:
    secret-key: sk_test_51SE48THRWMzXfAFedGPQ02RwkGnexkJXFeFi6ckainh6NN2dEcGt1if7C8ZqHeRBTbiUmJCaPBibr6nQsgLp5ena00X7YwcW11
    client-id: ca_TAak0BWyIkV04HPOSCWKapGXV2D3VEPU


server:
  port: 18081